server:
  port: 8085
spring:
  application:
    name: conference
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 6
        max-wait: -1ms
    timeout: 60s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
